### ISSUE TITLE
Fehler bei Admidio3.3

### ISSUE THREAD

**Issue by sistlind** [rmbinder/Geburtstagsliste#21]
Hallo,
mit der Admidio Version 3.3 sieht die Geburtstagsliste bei mir so aus:
![bildschirmfoto vom 2018-04-16 19-58-56](https://user-images.githubusercontent.com/6959674/38826638-b5d49090-41b0-11e8-8888-fc7074f4b666.png)

Habe auch schon einmal komplett deinstalliert, hat aber nichts geholfen.

An was kann das liegen?

Gruß Stefan

**Comment by rmbinder** [comment]
Hallo Stefan,

hast Du Admidio nach der Installation neu gestartet? Bei mir war ein 
Neustart erforderlich.

Viele Grüße

Rainer


Am 16.04.2018 um 20:00 schrieb Stefan Lindner:

**Comment by sistlind** [comment]
Hi,
nach einem erneuten Login in einer frischen Browser-session ist es besser, aber noch nicht ganz weg:
![grafik](https://user-images.githubusercontent.com/6959674/38881923-41d0f9c2-4269-11e8-8ad0-9fe400199d53.png)


Und die WArnung zeigt es auch noch an:
Notice: Undefined variable: javascriptCode in /home/webtyujdk/html/admidio/adm_plugins/geburtstagsliste/preferences.php on line 155
