### ISSUE TITLE
Menu Items not translated 

### ISSUE THREAD

**Issue by robertoschwald** [rmbinder/Geburtstagsliste#32]
Installed plugin version 3.1.0 into Admidio 4.0.1.
The menu items are not translated. 
The languages xml files are unpacked correctly into adm_plugins/geburtstagsliste/languages.

Error log:
```
Admidio.ERROR: L10N: Could not found text-id! {"textId":"PLG_GEBURTSTAGSLISTE_DOCUMENTATION_OPEN"} {"file":".../admidio/adm_program/system/classes/Language.php","line":119,"class":"Language","function":"get"}
Admidio.ERROR: L10N: Could not found text-id! {"textId":"PLG_GEBURTSTAGSLISTE_DOCUMENTATION"} {"file":".../admidio/adm_program/system/classes/Language.php","line":119,"class":"Language","function":"get"}
Admidio.ERROR: L10N: Could not found text-id! {"textId":"PLG_GEBURTSTAGSLISTE_DOCUMENTATION_OPEN_DESC"} {"file":".../admidio/adm_program/system/classes/Language.php","line":119,"class":"Language","function":"get"}
Admidio.ERROR: L10N: Could not found text-id! {"textId":"PLG_GEBURTSTAGSLISTE_PLUGIN_INFORMATION"} {"file":".../admidio/adm_program/system/classes/Language.php","line":119,"class":"Language","function":"get"}
```

<img width="1397" alt="geblist_trans" src="https://user-images.githubusercontent.com/1519879/103170909-435dd480-4848-11eb-9a8f-bc4c931026c5.png">

**Comment by rmbinder** [comment]
The most common cause of this error message is the cache. Clear your browser's cache.

**Comment by robertoschwald** [comment]
Really? I get PhP errors that translations are not found. So imho. Ot browser cache related. This is a brand new install.

**Comment by rmbinder** [comment]
This [thread](https://www.admidio.org/forum/viewtopic.php?f=10&t=8110&p=29105&hilit=%23PLG_GEBURTSTAGSLISTE#p29105) addresses the same problem. I also described a workaround with "addLanguageFolderPath" in it.

**Comment by robertoschwald** [comment]
Right. After deleting the ADMIDIO_GSK_gskera_admidio_adm_SESSION_ID cookie, it works. Strange.
